import { useCallback, useEffect, useState } from 'react'
import type { ResourceSearchHit, ResourceVersion, SiteDossier } from '../../../shared/contracts/resources'

export function KnowledgePanel(): React.JSX.Element {
  const [workspaceId, setWorkspaceId] = useState(''); const [dossiers, setDossiers] = useState<SiteDossier[]>([]); const [resources, setResources] = useState<ResourceVersion[]>([]); const [hits, setHits] = useState<ResourceSearchHit[]>([]); const [coverage, setCoverage] = useState<Record<string, unknown> | null>(null); const [query, setQuery] = useState(''); const [origin, setOrigin] = useState(''); const [note, setNote] = useState('')
  const action = useCallback(async (name: string, input: Record<string, unknown> = {}) => { const ws = await window.monitor.getWorkspaces(); const id = ws.output?.activeWorkspaceId; if (!id) throw new Error('没有活动工作区'); setWorkspaceId(id); return window.monitor.executeAction({ action: name, input, target: { kind: 'workspace', workspaceId: id } }) }, [])
  const refresh = useCallback(async () => { const [summary, list] = await Promise.all([action('resources.summary'), action('resources.list', { origin: origin || undefined, limit: 200 })]); const a = summary.output as { dossiers?: SiteDossier[]; coverage?: Record<string, unknown> } | null; const b = list.output as { rows?: ResourceVersion[] } | null; setDossiers(a?.dossiers ?? []); setCoverage(a?.coverage ?? null); setResources(b?.rows ?? []) }, [action, origin])
  useEffect(() => { void refresh() }, [refresh])
  const rebuild = async () => { setNote('正在从原始证据重建索引…'); const result = await action('resources.rebuild'); setNote(result.task.error?.message ?? `索引完成：${JSON.stringify(result.output)}`); await refresh() }
  const search = async () => { const result = await action('resources.search', { query, origin: origin || undefined, limit: 100 }); const output = result.output as { rows?: ResourceSearchHit[]; coverage?: Record<string, unknown> } | null; setHits(output?.rows ?? []); setCoverage(output?.coverage ?? null); setNote(result.task.error?.message ?? `命中 ${(output?.rows ?? []).length} 条`) }
  const addNote = async (resource: ResourceVersion) => { const text = window.prompt('资源笔记'); if (!text) return; const result = await action('resources.noteSave', { resourceId: resource.id, origin: resource.origin, text }); setNote(result.task.error?.message ?? '笔记已保存为新版本') }
  return <div className="sp-panel"><div className="sp-bar"><button className="tab" onClick={() => void rebuild()}>重建索引</button><input className="filter-text" value={query} placeholder="搜索中文、源码或 URL" onChange={(event) => setQuery(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter') void search() }} /><button className="tab" disabled={!query} onClick={() => void search()}>搜索</button><select value={origin} onChange={(event) => setOrigin(event.target.value)}><option value="">全部站点</option>{dossiers.map((item) => <option key={item.origin}>{item.origin}</option>)}</select></div>{note ? <div className="rules-note">{note}</div> : null}<div className="sp-layout"><div className="sp-origins"><strong>站点档案</strong>{dossiers.map((item) => <button key={item.origin} className={'sp-origin' + (origin === item.origin ? ' is-active' : '')} onClick={() => setOrigin(item.origin)}><span className="sp-origin-name">{item.origin}</span><small>{item.versions} 版本 · {item.visits} 证据</small></button>)}</div><div className="sp-detail"><div className="sp-body"><p className="mono small">workspace={workspaceId || '-'} · coverage={coverage ? JSON.stringify(coverage) : '尚未构建'}</p>{(hits.length ? hits.map((item) => item.resource) : resources).map((item) => <div className="sp-line" key={item.id}><div><strong>{item.path}</strong><div className="mono small">v{item.version} · {item.resourceType ?? 'Other'} · {item.mimeType ?? '-'} · seq {item.evidence[0]?.seq ?? '-'}</div>{hits.find((hit) => hit.resource.id === item.id)?.snippet ? <pre>{hits.find((hit) => hit.resource.id === item.id)?.snippet}</pre> : null}</div><button className="tab" onClick={() => void addNote(item)}>笔记</button></div>)}</div></div></div></div>
}

