import { useCallback, useEffect, useState } from 'react'
import type { ReplayTemplate } from '../../../shared/contracts/replay'
import type { TestSuite } from '../../../shared/contracts/testing'

export function ReplayPanel({ selectedSeq }: { selectedSeq: number | null }): React.JSX.Element {
  const [workspaceId, setWorkspaceId] = useState(''); const [templates, setTemplates] = useState<ReplayTemplate[]>([]); const [runs, setRuns] = useState<Array<Record<string, unknown>>>([]); const [tests, setTests] = useState<TestSuite[]>([]); const [reports, setReports] = useState<Array<Record<string, unknown>>>([]); const [selected, setSelected] = useState(''); const [editor, setEditor] = useState(''); const [importText, setImportText] = useState(''); const [note, setNote] = useState('')
  const refresh = useCallback(async () => { const ws = await window.monitor.getWorkspaces(); const id = ws.output?.activeWorkspaceId; if (!id) return; setWorkspaceId(id); const target = { kind: 'workspace' as const, workspaceId: id }; const [replay, testing] = await Promise.all([window.monitor.executeAction({ action: 'replay.list', input: {}, target }), window.monitor.executeAction({ action: 'tests.list', input: {}, target })]); const list = (replay.output as { templates?: ReplayTemplate[]; runs?: Array<Record<string, unknown>> } | null); setTemplates(list?.templates ?? []); setRuns(list?.runs ?? []); const testList = testing.output as { suites?: TestSuite[]; runs?: Array<Record<string, unknown>> } | null; setTests(testList?.suites ?? []); setReports(testList?.runs ?? []) }, [])
  useEffect(() => { void refresh() }, [refresh])
  const derive = async () => { if (!workspaceId || selectedSeq === null) return; const result = await window.monitor.executeAction({ action: 'replay.createFromRequest', input: { seq: selectedSeq }, target: { kind: 'workspace', workspaceId } }); setNote(result.task.error?.message ?? '已派生模板'); await refresh() }
  const save = async () => { try { const value = JSON.parse(editor); const result = await window.monitor.executeAction({ action: 'replay.save', input: value, target: { kind: 'workspace', workspaceId } }); setNote(result.task.error?.message ?? '已保存新版本'); await refresh() } catch (error) { setNote(String(error)) } }
  const importRequests = async (format: 'curl' | 'har') => { const result = await window.monitor.executeAction({ action: 'replay.import', input: { format, source: importText }, target: { kind: 'workspace', workspaceId } }); setNote(result.task.error?.message ?? `已导入 ${(result.output as unknown[] | null)?.length ?? 0} 个模板`); if (!result.task.error) setImportText(''); await refresh() }
  const run = async (mode: 'browser' | 'independent') => { const template = templates.filter((item) => item.id === selected).sort((a, b) => b.version - a.version)[0]; if (!template) return; const result = await window.monitor.executeAction({ action: 'replay.run', input: { templateId: template.id, version: template.version, mode, confirmWrite: true }, target: { kind: 'workspace', workspaceId } }); setNote(result.task.error?.message ?? `运行：${(result.output as { state?: string })?.state}`); await refresh() }
  const makeSuite = async () => { if (!selected) return; const input = { name: '快速回归', templateId: selected, mode: 'independent', iterations: 10, concurrency: 2, intervalMs: 0, retries: 0, stopOnFailure: false, datasets: [{}], assertions: [{ kind: 'status', op: 'between', value: 200, max: 399 }] }; const result = await window.monitor.executeAction({ action: 'tests.save', input, target: { kind: 'workspace', workspaceId } }); setNote(result.task.error?.message ?? '已创建 10 次快速回归'); await refresh() }
  const runSuite = async (suite: TestSuite) => { const result = await window.monitor.executeAction({ action: 'tests.run', input: { suiteId: suite.id, version: suite.version }, target: { kind: 'workspace', workspaceId } }); setNote(result.task.error?.message ?? JSON.stringify((result.output as { summary?: unknown })?.summary)); await refresh() }
  return <div className="sp-panel"><div className="sp-bar"><button className="tab" disabled={selectedSeq === null} onClick={() => void derive()}>从当前请求派生</button><button className="tab" disabled={!editor} onClick={() => void save()}>保存新版本</button><button className="tab" disabled={!selected} onClick={() => void run('browser')}>浏览器重放</button><button className="tab" disabled={!selected} onClick={() => void run('independent')}>独立重放</button><button className="tab" disabled={!selected} onClick={() => void makeSuite()}>创建批量测试</button></div>{note ? <div className="rules-note">{note}</div> : null}<div className="sp-layout"><div className="sp-origins">{templates.map((item) => <button key={`${item.id}-${item.version}`} className={'sp-origin' + (selected === item.id ? ' is-active' : '')} onClick={() => { setSelected(item.id); const { createdAt: _c, updatedAt: _u, ...editable } = item; setEditor(JSON.stringify(editable, null, 2)) }}><span className="sp-origin-name">{item.name}</span><small>{item.method} · v{item.version}</small></button>)}</div><div className="sp-detail"><textarea className="rules-textarea replay-editor" value={editor} onChange={(event) => setEditor(event.target.value)} spellCheck={false} /><div className="sp-body"><h4>安全导入</h4><textarea className="rules-textarea" placeholder="粘贴 cURL 或 HAR；只解析，不执行命令" value={importText} onChange={(event) => setImportText(event.target.value)} /><div className="sp-line"><button className="tab" disabled={!importText} onClick={() => void importRequests('curl')}>导入 cURL</button><button className="tab" disabled={!importText} onClick={() => void importRequests('har')}>导入 HAR</button></div><h4>测试套件</h4>{tests.map((suite) => <div className="sp-line" key={`${suite.id}-${suite.version}`}><span>{suite.name} · {suite.iterations} 次 × {suite.concurrency}</span><button className="tab" onClick={() => void runSuite(suite)}>运行</button></div>)}<h4>最近运行</h4>{[...reports, ...runs].slice(0, 20).map((run, index) => <pre className="sp-line" key={String(run['id'] ?? index)}>{JSON.stringify(run['summary'] ?? { state: run['state'], id: run['id'] })}</pre>)}</div></div></div></div>
}
