import { useCallback, useEffect, useState } from 'react'
import type { WorkflowDefinition, WorkflowRun } from '../../../shared/contracts/workflow'

const SAMPLE = { name: '资源索引与检索', nodes: [{ id: 'index', kind: 'action', action: 'resources.rebuild', input: {} }, { id: 'search', kind: 'action', action: 'resources.search', input: { query: '${keyword}', limit: 20 }, dependsOn: ['index'], extract: { hitCount: 'total' } }] }

export function WorkflowPanel(): React.JSX.Element {
  const [workspaceId, setWorkspaceId] = useState(''); const [definitions, setDefinitions] = useState<WorkflowDefinition[]>([]); const [runs, setRuns] = useState<WorkflowRun[]>([]); const [editor, setEditor] = useState(JSON.stringify(SAMPLE, null, 2)); const [note, setNote] = useState('')
  const action = useCallback(async (name: string, input: Record<string, unknown> = {}) => { const ws = await window.monitor.getWorkspaces(); const id = ws.output?.activeWorkspaceId; if (!id) throw new Error('没有活动工作区'); setWorkspaceId(id); return window.monitor.executeAction({ action: name, input, target: { kind: 'workspace', workspaceId: id } }) }, [])
  const refresh = useCallback(async () => { const result = await action('workflow.list'); const output = result.output as { definitions?: WorkflowDefinition[]; runs?: WorkflowRun[] } | null; setDefinitions(output?.definitions ?? []); setRuns(output?.runs ?? []) }, [action])
  useEffect(() => { void refresh() }, [refresh])
  const save = async () => { try { const result = await action('workflow.save', JSON.parse(editor)); setNote(result.task.error?.message ?? '工作流新版本已保存'); await refresh() } catch (error) { setNote(String(error)) } }
  const start = async (definition: WorkflowDefinition) => { setNote('工作流运行中…'); const result = await action('workflow.start', { workflowId: definition.id, version: definition.version, variables: { keyword: 'json' } }); setNote(result.task.error?.message ?? `运行结束：${(result.output as WorkflowRun | null)?.state}`); await refresh() }
  const takeover = async (run: WorkflowRun) => { const result = await action('workflow.command', { runId: run.id, command: 'takeover' }); setNote(result.task.error?.message ?? '已由人类接管，旧租约失效'); await refresh() }
  return <div className="sp-panel"><div className="sp-bar"><button className="tab" onClick={() => void save()}>保存工作流版本</button><span className="mono small">workspace={workspaceId || '-'}</span></div>{note ? <div className="rules-note">{note}</div> : null}<div className="sp-layout"><div className="sp-origins"><strong>流程版本</strong>{definitions.map((item) => <button className="sp-origin" key={`${item.id}-${item.version}`} onClick={() => setEditor(JSON.stringify({ id: item.id, name: item.name, nodes: item.nodes }, null, 2))}><span className="sp-origin-name">{item.name}</span><small>v{item.version} · {item.nodes.length} 节点</small></button>)}</div><div className="sp-detail"><textarea className="rules-textarea replay-editor" value={editor} onChange={(event) => setEditor(event.target.value)} spellCheck={false} /><div className="sp-body"><h4>运行时间线</h4>{definitions.slice(-5).map((item) => <button className="tab" key={`${item.id}-${item.version}`} onClick={() => void start(item)}>运行 {item.name} v{item.version}</button>)}{runs.map((run) => <div className="sp-line" key={run.id}><div><strong>{run.state} · {run.owner}</strong><div className="mono small">{run.id} · fencing {run.lease} · {run.nodes.map((item) => `${item.nodeId}:${item.state}`).join(' → ')}</div></div><button className="tab" onClick={() => void takeover(run)}>接管</button></div>)}</div></div></div></div>
}

