import { readFileSync } from 'node:fs'
const o = JSON.parse(readFileSync('C:/Users/22478/Documents/Codex/2026-09-19/i/work/smoke-dom.json', 'utf8'))
console.log('tree', JSON.stringify({ ok: o.tree.ok, err: o.tree.error, rows: o.tree.rows, domains: o.tree.domains }))
console.log('tree rows:', o.tree.rows)
console.log('tree rowsSample:', o.tree.rowsSample.map((r) => [r.nodeId, r.depth, r.nodeType, r.label, r.expandable, r.expanded, r.preview ?? '']))
console.log('kids', JSON.stringify({ ok: o.kids.ok, rows: o.kids.rows, domains: o.kids.domains }))
console.log('kids first:', o.kids.first.map((r) => [r.nodeId, r.depth, r.nodeType, r.label, r.expandable]))
console.log('style ok/ms/domains', o.style.ok, o.style.ms, o.style.domains)
console.log('style node:', o.style.node)
console.log('style html:', o.style.html)
console.log('style box:', JSON.stringify(o.style.box))
console.log('style matched:', JSON.stringify(o.style.matched, null, 1))
console.log('inline matched:', JSON.stringify(o.inlineMatched, null, 1))
console.log('btn listeners:', JSON.stringify(o.btn, null, 1))
console.log('miss:', JSON.stringify(o.miss))
console.log('bad:', JSON.stringify(o.bad))
console.log('highlight:', JSON.stringify(o.highlight))
console.log('sessions.current:', o.sessions.current, 'instances:', o.sessions.instances.length, 'storage.tables:', JSON.stringify(o.sessions.storage.tables), 'targets:', o.sessions.targets.length)
