export default [
  {
    file: 'src/main/control/bridge.ts',
    label: 'import 类型',
    old: "import type { ControllerStatus, InputAction, Profile, RequestQuery, RequestOrder, RuleSet, ScreenshotOptions, ScriptQuery, ScriptOrder } from '../../shared/types'",
    new: "import type {\n  ControllerStatus,\n  EventQuery,\n  InputAction,\n  Profile,\n  RequestQuery,\n  RequestOrder,\n  RuleSet,\n  ScreenshotOptions,\n  ScriptOrder,\n  ScriptQuery,\n  WsFrameQuery\n} from '../../shared/types'"
  },
  {
    file: 'src/main/control/bridge.ts',
    label: '可选数字转换',
    old: 'export class ControlBridge {',
    new: "/** 控制面传进来的是字符串/undefined，统一收成可选数字 —— 别把 undefined 变成 NaN */\nfunction numOrUndefined(value: unknown): number | undefined {\n  if (value === undefined || value === null || value === '') return undefined\n  const n = Number(value)\n  return Number.isFinite(n) ? n : undefined\n}\n\nexport class ControlBridge {"
  },
  {
    file: 'src/main/control/bridge.ts',
    label: '新增 callApi 分支',
    old: "      case 'sessions.switchProfile':\n        return api.switchProfile((p.profile === 'H' ? 'H' : 'L') as Profile)",
    new: [
      "      case 'sessions.switchProfile':",
      "        return api.switchProfile((p.profile === 'H' ? 'H' : 'L') as Profile)",
      '',
      '      /* ---- 事件流 / WebSocket ---- */',
      '',
      "      case 'events.query':",
      "        return api.queryEvents((p.query ?? {}) as EventQuery)",
      "      case 'eventStats':",
      '        return api.getEventStats()',
      "      case 'ws.query':",
      "        return api.queryWsFrames((p.query ?? {}) as WsFrameQuery)",
      "      case 'ws.connections':",
      '        return api.getWsConnections(numOrUndefined(p.limit))',
      '',
      '      /* ---- 分析：画像 / 调用图 / 关联 ---- */',
      '',
      "      case 'endpoints.profiles':",
      '        return api.getEndpointProfiles({',
      '          query: p.query as RequestQuery | undefined,',
      '          sort: p.sort === undefined ? undefined : String(p.sort),',
      '          minCalls: numOrUndefined(p.minCalls),',
      '          limit: numOrUndefined(p.limit),',
      '          maxRows: numOrUndefined(p.maxRows)',
      '        })',
      "      case 'endpoint.detail':",
      "        return api.getEndpointDetail(String(p.key ?? ''), {",
      '          query: p.query as RequestQuery | undefined,',
      '          sampleLimit: numOrUndefined(p.sampleLimit),',
      '          callLimit: numOrUndefined(p.callLimit),',
      '          maxRows: numOrUndefined(p.maxRows)',
      '        })',
      "      case 'graph':",
      '        return api.getRequestGraph({',
      '          query: p.query as RequestQuery | undefined,',
      '          maxRows: numOrUndefined(p.maxRows),',
      '          maxNodes: numOrUndefined(p.maxNodes)',
      '        })',
      "      case 'relations':",
      '        return api.getRelations({',
      '          query: p.query as RequestQuery | undefined,',
      '          maxRows: numOrUndefined(p.maxRows),',
      '          limit: numOrUndefined(p.limit)',
      '        })',
      '',
      '      /* ---- 导出 ---- */',
      '',
      "      case 'export.har':",
      '        return api.exportHar({',
      '          query: p.query as RequestQuery | undefined,',
      '          maxRows: numOrUndefined(p.maxRows),',
      '          includeBodies: p.includeBodies !== false',
      '        })',
      "      case 'export.jsonl':",
      '        return api.exportJsonl({',
      '          query: p.query as RequestQuery | undefined,',
      '          maxRows: numOrUndefined(p.maxRows),',
      '          includeBodies: p.includeBodies !== false',
      '        })',
      "      case 'export.bodies':",
      '        return api.exportBodies({',
      '          query: p.query as RequestQuery | undefined,',
      '          maxRows: numOrUndefined(p.maxRows),',
      '          includeBodies: p.includeBodies !== false,',
      '          dir: p.dir === undefined ? undefined : String(p.dir)',
      '        })',
      '',
      '      /* ---- 契约快照与回归 ---- */',
      '',
      "      case 'contract.snapshot':",
      '        return api.contractSnapshot({',
      '          label: p.label === undefined ? undefined : String(p.label),',
      '          query: p.query as RequestQuery | undefined,',
      '          sampleLimit: numOrUndefined(p.sampleLimit)',
      '        })',
      "      case 'contract.list':",
      '        return api.listContracts(numOrUndefined(p.limit))',
      "      case 'contract.get':",
      '        return api.getContract(Number(p.id), p.withSchema !== false)',
      "      case 'contract.delete':",
      '        return api.deleteContract(Number(p.id))',
      "      case 'contract.diff':",
      '        return api.contractDiff({',
      '          baseId: Number(p.baseId),',
      '          query: p.query as RequestQuery | undefined,',
      '          sampleLimit: numOrUndefined(p.sampleLimit)',
      '        })',
      '',
      '      /* ---- 对话框 ---- */',
      '',
      "      case 'dialog.handle':",
      '        return api.handleDialog(p.accept !== false, p.promptText === undefined ? undefined : String(p.promptText))'
    ].join('\n')
  }
]