/**
 * 类型定义：分析层（事件流 / WS / 画像 / 调用图 / 关联 / 导出 / 契约）。
 */
const TYPES_BLOCK = [
  '',
  '/* ------------------------------------------------- 事件流与 WebSocket */',
  '',
  '/** 事件流的 kind。列成联合类型是为了让采集侧和面板别各写一套字符串 */',
  'export type MonitorEventKind =',
  "  | 'navigation'",
  "  | 'console'",
  "  | 'exception'",
  "  | 'websocket'",
  "  | 'download'",
  "  | 'dialog'",
  "  | 'target'",
  "  | 'rule'",
  "  | 'overflow'",
  '',
  'export interface MonitoredEvent {',
  '  /** 库里的自增 id（增量拉取的游标）。刚采集还没落库时没有 */',
  '  id?: number',
  '  ts: number',
  '  kind: MonitorEventKind',
  "  level?: 'info' | 'warn' | 'error'",
  '  targetType?: string',
  '  url?: string',
  '  detail?: unknown',
  '}',
  '',
  'export interface EventQuery {',
  '  /** 只管要 id 比它大的（增量拉取）。上一次返回里的 nextSince 直接拿来用 */',
  '  since?: number',
  '  until?: number',
  '  kinds?: MonitorEventKind[]',
  '  kind?: MonitorEventKind',
  '  level?: string',
  '  targetType?: string',
  '  search?: string',
  '  limit?: number',
  "  order?: 'asc' | 'desc'",
  '}',
  '',
  'export interface EventPage {',
  '  rows: MonitoredEvent[]',
  '  /** 库里当前最大的事件 id */',
  '  latest: number',
  '  /** 下一次该带的 since */',
  '  nextSince: number',
  '  total: number',
  '}',
  '',
  'export interface EventStats {',
  '  rows: Array<{',
  '    kind: string',
  '    level: string | null',
  '    count: number',
  '    firstTs: number | null',
  '    lastTs: number | null',
  '    latestId: number',
  '  }>',
  '  latest: number',
  '  total: number',
  '}',
  '',
  'export interface WsFrameRecord {',
  '  seq?: number',
  '  ts: number',
  '  requestId: string',
  '  url?: string',
  "  direction: 'sent' | 'received'",
  '  opcode: number',
  '  /** 文本帧是原文；二进制帧是 base64（CDP 的约定），用 binary 区分 */',
  '  payload: string',
  '  /** 真实载荷字节数（二进制帧已按 base64 换算回解码后的长度） */',
  '  size: number',
  '  truncated: boolean',
  '  binary: boolean',
  '}',
  '',
  'export interface WsFrameRow extends WsFrameRecord {',
  '  id: number',
  '  opcodeName: string',
  '}',
  '',
  'export interface WsFrameQuery {',
  '  since?: number',
  '  direction?: string',
  '  requestId?: string',
  '  opcode?: number',
  '  search?: string',
  '  limit?: number',
  "  order?: 'asc' | 'desc'",
  '}',
  '',
  'export interface WsFramePage {',
  '  rows: WsFrameRow[]',
  '  latest: number',
  '  nextSince: number',
  '  total: number',
  '}',
  '',
  '/** 一条 WS 连接的汇总。面板先列连接、点开再看帧 */',
  'export interface WsConnectionRow {',
  '  requestId: string',
  '  url: string',
  '  frames: number',
  '  sent: number',
  '  received: number',
  '  binaryFrames: number',
  '  truncatedFrames: number',
  '  bytes: number',
  '  firstTs: number',
  '  lastTs: number',
  '  seq: number | null',
  '}',
  '',
  '/* ------------------------------------------------------------ 接口画像 */',
  '',
  'export interface FieldDistribution {',
  '  name: string',
  '  count: number',
  '  /** 每一个「有 body / 有 query」的样本里都出现才算必填 */',
  '  required: boolean',
  '  values: string[]',
  '}',
  '',
  '/** JSON 形状。object 带 fields、array 带 items，其余 t 就是叶子类型 */',
  'export interface JsonSchemaNode {',
  '  t: string',
  '  count?: number',
  '  seen?: number',
  '  len?: number',
  '  items?: JsonSchemaNode | null',
  '  fields?: Record<string, JsonSchemaNode>',
  '  of?: JsonSchemaNode[]',
  '}',
  '',
  'export interface SchemaPath {',
  '  path: string',
  '  type: string',
  '  /** 样本里不是每次都有 */',
  '  optional: boolean',
  '}',
  '',
  'export interface EndpointProfile {',
  '  key: string',
  '  calls: number',
  '  distinctUrls: number',
  '  sampleUrls: string[]',
  '  samples: number[]',
  '  statuses: Array<{ key: string; count: number }>',
  '  mimeTypes: Array<{ key: string; count: number }>',
  '  resourceTypes: Array<{ key: string; count: number }>',
  '  targetTypes: Array<{ key: string; count: number }>',
  '  durationMs: { p50: number | null; p95: number | null; min: number | null; max: number | null }',
  '  bytes: number',
  '  decodedBytes: number',
  '  failed: number',
  '  cached: number',
  '  fromSw: number',
  '  withBody: number',
  '  query: FieldDistribution[]',
  '  requestBody: {',
  '    samples: number',
  '    kinds: Array<{ key: string; count: number }>',
  '    fields: FieldDistribution[]',
  '  }',
  '  /** 调用节奏（中位间隔）。看的是「这个接口是不是在被轮询」 */',
  '  rhythm: { medianGapMs: number; spanMs: number } | null',
  '  firstTs: number | null',
  '  lastTs: number | null',
  '}',
  '',
  'export interface EndpointPage {',
  '  endpoints: EndpointProfile[]',
  '  /** 过滤后剩下的端点数（可能大于返回的条数） */',
  '  matched: number',
  '  scanned: number',
  '  total: number',
  '  /** 实例里还有行没被扫到（maxRows 之外） */',
  '  truncated: boolean',
  '  sort: string',
  '}',
  '',
  'export interface EndpointCallSample {',
  '  seq: number',
  '  ts: number',
  '  url: string',
  '  status: number | null',
  '  durationMs: number | null',
  '  ttfbMs: number | null',
  '  bytes: number | null',
  '  fromCache: boolean',
  '  fromSw: boolean',
  '  bodyState: string | null',
  '  targetType: string | null',
  '  failed: string | null',
  '}',
  '',
  'export interface EndpointDetail {',
  '  key: string',
  '  found: boolean',
  '  error?: string',
  '  totalCalls?: number',
  '  profile?: EndpointProfile',
  '  recent?: EndpointCallSample[]',
  '  responseSchema?: JsonSchemaNode | null',
  '  responseFields?: SchemaPath[]',
  '  responseSamples?: number',
  '  responseSamplesSkipped?: number',
  '  requestSchema?: JsonSchemaNode | null',
  '  requestSamples?: number',
  '  truncated?: boolean',
  '}',
  '',
  '/* -------------------------------------------------------------- 调用图 */',
  '',
  'export interface GraphNode {',
  '  key: string',
  '  /** endpoint / script / document / 其它 initiator 类型 */',
  '  kind: string',
  '  label: string',
  '  url: string | null',
  '  host: string | null',
  '  method: string | null',
  '  functionName: string | null',
  '  outCalls: number',
  '  inCalls: number',
  '}',
  '',
  'export interface GraphEdge {',
  '  from: string',
  '  to: string',
  '  count: number',
  '  failures: number',
  '  avgMs: number | null',
  '  p95Ms: number | null',
  '  initiatorTypes: Array<{ key: string; count: number }>',
  '  samples: number[]',
  '  firstTs: number | null',
  '  lastTs: number | null',
  '}',
  '',
  'export interface RequestGraph {',
  '  nodes: GraphNode[]',
  '  edges: GraphEdge[]',
  '  /** 连通分量 = 互相牵动的「功能簇」 */',
  '  clusters: Array<{ size: number; nodes: string[] }>',
  '  scanned: number',
  '  total: number',
  '  truncated: boolean',
  '  droppedNodes: number',
  '}',
  '',
  'export interface RelationReport {',
  '  sharedBodies: Array<{',
  '    hash: string',
  '    refs: number',
  '    size: number | null',
  '    distinctUrls: number',
  '    sampleUrls: string[]',
  '    endpoints: string[]',
  '    samples: number[]',
  '  }>',
  '  redirectChains: Array<{',
  '    requestId: string',
  '    hops: number',
  '    steps: Array<{ seq: number; method: string; url: string; status: number | null }>',
  '  }>',
  '  domainLinks: Array<{ frameHost: string; host: string; count: number }>',
  '  sharedParams: Array<{',
  '    name: string',
  '    value: string',
  '    count: number',
  '    endpoints: string[]',
  '    endpointCount: number',
  '    hosts: string[]',
  '    crossHost: boolean',
  '  }>',
  '  scanned: number',
  '  total: number',
  '  truncated: boolean',
  '}',
  '',
  '/* ---------------------------------------------------------------- 导出 */',
  '',
  'export interface ExportQuery {',
  '  /** 只导匹配的请求。不认识的字段会被忽略 */',
  '  query?: RequestQuery',
  '  /** 一次最多扫多少行（有上限，超了会报 truncated） */',
  '  maxRows?: number',
  '  includeBodies?: boolean',
  '}',
  '',
  'export interface HarExportReport {',
  '  path: string',
  '  bytes: number',
  '  entries: number',
  '  pages: number',
  '  /** 有 body_hash 但 blob 已被 LRU 淘汰掉的条数 */',
  '  bodyMissing: number',
  '  scanned: number',
  '  total: number',
  '  truncated: boolean',
  '  sample: Array<{ url: string; status: number; resourceType?: string }>',
  '}',
  '',
  'export interface JsonlExportReport {',
  '  path: string',
  '  bytes: number',
  '  lines: number',
  '  bodyMissing: number',
  '  scanned: number',
  '  total: number',
  '  truncated: boolean',
  '}',
  '',
  'export interface ResourceExportReport {',
  '  dir: string',
  '  manifest: string',
  '  files: number',
  '  bytes: number',
  '  skipped: number',
  '  total: number',
  '  truncated: boolean',
  '}',
  '',
  '/* ------------------------------------------------------------ 契约回归 */',
  '',
  'export interface ContractSummary {',
  '  id: number',
  '  label: string',
  '  inst: number',
  '  createdAt: number',
  '  endpoints: number',
  '  calls: number',
  '  truncated: boolean',
  '}',
  '',
  'export interface ContractListRow {',
  '  id: number',
  '  label: string',
  '  inst: number',
  '  createdAt: number',
  '  bytes: number',
  '}',
  '',
  'export interface ContractDiff {',
  '  base: { id: number | null; label: string | null; createdAt: number; endpoints: number }',
  '  current: { createdAt: number; endpoints: number; calls: number }',
  '  added: Array<{ key: string; calls: number; statuses: string[]; mimeTypes: string[] }>',
  '  removed: Array<{ key: string; calls: number; statuses: string[]; mimeTypes: string[] }>',
  '  changed: Array<{',
  '    key: string',
  '    statuses: { added: string[]; removed: string[] }',
  '    mimeTypes: { added: string[]; removed: string[] }',
  '    query: {',
  '      added: Array<{ name: string; required: boolean; samples: string[] }>',
  '      removed: Array<{ name: string }>',
  '      requiredChanged: Array<{ name: string; from: boolean; to: boolean }>',
  '    }',
  '    requestFields: {',
  '      added: Array<{ name: string; required: boolean; samples: string[] }>',
  '      removed: Array<{ name: string }>',
  '      requiredChanged: Array<{ name: string; from: boolean; to: boolean }>',
  '    }',
  '    response: {',
  '      added: SchemaPath[]',
  '      removed: SchemaPath[]',
  '      typeChanged: Array<{ path: string; from: string; to: string }>',
  '    }',
  '    callsBefore: number',
  '    callsAfter: number',
  '  }>',
  '  summary: {',
  '    addedEndpoints: number',
  '    removedEndpoints: number',
  '    changedEndpoints: number',
  '    unchangedEndpoints: number',
  '    addedEndpointKeys: string[]',
  '    removedEndpointKeys: string[]',
  '    newStatusCodes: string[]',
  '    droppedStatusCodes: string[]',
  '    newResponseFields: string[]',
  '    droppedResponseFields: string[]',
  '    newRequestFields: string[]',
  '    newQueryParams: string[]',
  '  }',
  '}'
].join('\n')

const API_BLOCK = [
  '',
  '  /* ---- 分析层：事件流 / WebSocket / 画像 / 调用图 / 关联 ---- */',
  '',
  '  /** 事件流（导航 / 控制台告警 / 异常 / 下载 / 对话框 / WS 生命周期）。since 给增量 */',
  '  queryEvents(query: EventQuery): Promise<EventPage | null>',
  '  getEventStats(): Promise<EventStats | null>',
  '  queryWsFrames(query: WsFrameQuery): Promise<WsFramePage | null>',
  '  getWsConnections(limit?: number): Promise<{ rows: WsConnectionRow[]; total: number } | null>',
  '  getEndpointProfiles(options?: {',
  '    query?: RequestQuery',
  '    sort?: string',
  '    minCalls?: number',
  '    limit?: number',
  '    maxRows?: number',
  '  }): Promise<EndpointPage | null>',
  '  getEndpointDetail(',
  '    key: string,',
  '    options?: { query?: RequestQuery; sampleLimit?: number; callLimit?: number; maxRows?: number }',
  '  ): Promise<EndpointDetail | null>',
  '  getRequestGraph(options?: {',
  '    query?: RequestQuery',
  '    maxRows?: number',
  '    maxNodes?: number',
  '  }): Promise<RequestGraph | null>',
  '  getRelations(options?: { query?: RequestQuery; maxRows?: number; limit?: number }): Promise<RelationReport | null>',
  '',
  '  /* ---- 导出与资源采集 ---- */',
  '',
  '  exportHar(options?: ExportQuery): Promise<HarExportReport>',
  '  exportJsonl(options?: ExportQuery): Promise<JsonlExportReport>',
  '  /** 把匹配到的响应体落成目录里的真文件 + manifest.json（离线镜像） */',
  '  exportBodies(options?: ExportQuery & { dir?: string }): Promise<ResourceExportReport>',
  '',
  '  /* ---- 接口契约：快照 + 回归 ---- */',
  '',
  '  contractSnapshot(options?: { label?: string; query?: RequestQuery; sampleLimit?: number }): Promise<ContractSummary>',
  '  listContracts(limit?: number): Promise<ContractListRow[] | null>',
  '  getContract(id: number, withSchema?: boolean): Promise<unknown>',
  '  deleteContract(id: number): Promise<{ deleted: number }>',
  '  contractDiff(options: { baseId: number; query?: RequestQuery; sampleLimit?: number }): Promise<ContractDiff>',
  '',
  '  /* ---- 对话框 ---- */',
  '',
  '  /** 应答（放行/取消）当前打开的 JS 对话框。不响应的话页面会一直卡住 */',
  '  handleDialog(accept: boolean, promptText?: string): Promise<{ ok: boolean; error?: string }>'
].join('\n')

export default [
  {
    file: 'src/shared/types.ts',
    label: 'StorageHealth 补事件与 WS 计数',
    old: '  scriptsDropped: number\n  scriptQueueDepth: number\n  lastFlushMs: number\n}',
    new: '  scriptsDropped: number\n  scriptQueueDepth: number\n  /** 事件流入库条数 / 队列满被丢的条数 */\n  eventsStored: number\n  eventsDropped: number\n  eventQueueDepth: number\n  /** WebSocket 帧入库条数 / 被丢的条数 */\n  wsFramesStored: number\n  wsFramesDropped: number\n  wsQueueDepth: number\n  lastFlushMs: number\n}'
  },
  {
    file: 'src/shared/types.ts',
    label: 'ControllerStatus 补事件与 WS 计数',
    old: '  /** 本次会话采集到的脚本条数（去重前） */\n  scriptCount: number',
    new: '  /** 本次会话采集到的脚本条数（去重前） */\n  scriptCount: number\n  /** 本次会话写进事件流的条数 */\n  eventCount?: number\n  /** 本次会话采集到的 WebSocket 帧数（含被上限丢掉的） */\n  wsFrameCount?: number'
  },
  {
    file: 'src/shared/types.ts',
    label: "PanelId 补 4 个面板",
    old: "  | 'dom'\n  | 'sessions'",
    new: "  | 'dom'\n  | 'sessions'\n  | 'events'\n  | 'ws'\n  | 'endpoints'\n  | 'graph'"
  },
  {
    file: 'src/shared/types.ts',
    label: 'ControllerApi 补分析层方法',
    old: '  /** 写界面偏好（浅合并），返回落盘后的完整设置 */\n  setUiSettings(patch: Partial<UiSettings>): Promise<UiSettings>\n}',
    new: '  /** 写界面偏好（浅合并），返回落盘后的完整设置 */\n  setUiSettings(patch: Partial<UiSettings>): Promise<UiSettings>\n' + API_BLOCK + '\n}'
  },
  {
    file: 'src/shared/types.ts',
    label: '追加分析层类型',
    old: 'export interface InputReport {',
    new: TYPES_BLOCK + '\n\nexport interface InputReport {'
  }
]